### ISSUE TITLE
github.com/rockl2e/ark-apisvr  package not exist ?

### ISSUE THREAD

**Issue by jiaojie1989** [longguikeji/arkid-broker#2]
/usr/local/Cellar/go/1.12.7/libexec/bin/go build [/Users/jiaojie/Projects/Golang/arkid-broker]
go: finding github.com/rockl2e/ark-apisvr v0.190515.1
go: github.com/rockl2e/ark-apisvr@v0.190515.1: unexpected status (https://mirrors.aliyun.com/goproxy/github.com/rockl2e/ark-apisvr/@v/v0.190515.1.info): 404 Not Found

**Comment by skoogi** [comment]
ACK

**Comment by skoogi** [comment]
https://github.com/longguikeji/arkid-broker/pull/3#issue-304968264
